name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:

    # 1 - Checkout code
    - name: Checkout code 
      uses: actions/checkout@v3

    # 2 - Set up python
    - name: Set up Python 3.11.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'
    
    # 3 - Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4 - Run tests
    - name: Run tests
      run: |
       pytest --maxfail=1 --disable-warnings -v

    # 5 - Linting
    - name: Run linting
      run: |
        black --check .
        isort --check-only .
        ruff check .

    # 6 - Build Docker image
    - name : Build Docker image
      run : | 
        docker build -t fastapi-app:test .
